- name: Deploy an web Application
  hosts: db_and_web_servers
  tasks:
    - name: Install Dependencies
      apt:
        name: [ 'python3-setuptools', 'python3-dev','python-apt','python3-distutils-extra','build-essential', 'python3-pip', 'python3', 'python3-pip' ]
        state: latest

    - name: Install mysql
      apt:
        name: ['python3-mysqldb','mysql-server','mysql-client']
        state: latest

      tags: mysql_user

    - name: Start mysql
      service:
        name: mysql
        state: started
        enabled: yes
      tags: mysql_user

    - name: Copy mysql cnf file
      copy: src=.my.cnf dest=/root/.my.cnf



    - name: Create mysql user
      mysql_user:
        login_user: root
        login_password: ''
        name: db_user
        password: Passw0rd
        priv: '*.*:ALL'
        host: '%'
        login_unix_socket: /var/run/mysqld/mysqld.sock
        state: present
      tags: mysql_user

    - name: Create a new database with name 'employee_db'
      mysql_db:
        login_unix_socket: /var/run/mysqld/mysqld.sock
        name: employee_db
        state: present
    - name: install pip3
      yum: name=python3-pip state=absent
    - name: install pip3
      yum: name=python3-pip state=latest

    - name: Install Flask dependencies
      pip:
        name: 'flask'
        state: latest
        executable: pip3